---
- name: "Update and upgrade packages"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: "Remove unwanted dependencies"
  become: yes
  apt:
    autoremove: yes
- name: "Install NodeJS and npm"
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
- name: "Extract artifact"
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .
- name: "Start app"
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
